# Bag of Words

## 1. Count Vectorizer

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['Grow your data science skills by competing in our exciting competitions.']

In [30]:
cvect = CountVectorizer()
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [31]:
output = cvect.fit_transform(corpus)

In [32]:
output.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [38]:
cvect.vocabulary_

{'grow': 5,
 'your': 10,
 'data': 3,
 'science': 8,
 'skills': 9,
 'by': 0,
 'competing': 1,
 'in': 6,
 'our': 7,
 'exciting': 4,
 'competitions': 2}

- 불용어 (Stopwords) 제거

In [39]:
# 자체 제거
cvect = CountVectorizer(stop_words=['by', 'in'])
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1 1]]
{'grow': 4, 'your': 8, 'data': 2, 'science': 6, 'skills': 7, 'competing': 0, 'our': 5, 'exciting': 3, 'competitions': 1}


In [44]:
# #### 최초로 nltk 작업을 한 경우에는 punkt, stopwords 모듈을 다운로드 받는다.
# import nltk
# nltk.download()

In [41]:
# NLTK에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw = stopwords.words('english')
len(sw), type(sw)

(179, list)

- 인덱스에 해당하는 단어는 무엇인지 알려주는 함수

In [42]:
# 딕셔너리 반복문
voca = cvect.vocabulary_
for key in voca.keys():
    print(key, voca[key])
    

grow 4
your 8
data 2
science 6
skills 7
competing 0
our 5
exciting 3
competitions 1


In [45]:
for key, value in voca.items():
    print(key, value)

grow 4
your 8
data 2
science 6
skills 7
competing 0
our 5
exciting 3
competitions 1


In [ ]:
for key, value in voca.items():
    

In [50]:

def get_word(index, voca):
    for key in voca:
        if voca[key] == index:
            return key
        
get_word(5,cvect.vocabulary_)

'our'

In [51]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key

get_word(5, cvect.vocabulary_)


'our'

- N-gram

In [52]:
text = ['I work at google.']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'work': 3, 'at': 0, 'google': 2, 'work at': 4, 'at google': 1}


In [53]:
text = ['I google at work.']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'google': 2, 'at': 0, 'work': 4, 'google at': 3, 'at work': 1}


In [54]:
text = ['I google at work.', 'I work at google']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 0 1 1 1 1 0]
 [1 1 0 1 0 1 1]]
{'google': 3, 'at': 0, 'work': 5, 'google at': 4, 'at work': 2, 'work at': 6, 'at google': 1}


### 2. TF-IDF Vectorizer

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ['you konw I want your love', ' I like you', 'what should I do']

In [57]:
cvect = CountVectorizer()
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'konw': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [58]:
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'konw': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [59]:
tvect = TfidfVectorizer(stop_words='english', ngram_range=(1,2))
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.4472136 0.4472136 0.        0.4472136 0.4472136 0.4472136]
 [0.        0.        1.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.       ]]
{'konw': 0, 'want': 4, 'love': 3, 'konw want': 1, 'want love': 5, 'like': 2}
